[package]
name = "glitch"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0", features = ["is_variant"] }
itertools = "0.14"
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.3"
